#!/bin/bash
#
# Test the Python image in the OpenShift.
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# VERSION specifies a version of the python in the candidate image.
# The image has to be available before this script is executed.

THISDIR=$(dirname ${BASH_SOURCE[0]})

source "${THISDIR}/test-lib.sh"
source "${THISDIR}/test-lib-openshift.sh"
source "${THISDIR}/test-lib-python.sh"
source "${THISDIR}/test-lib-remote-openshift.sh"

TEST_LIST="\
test_python_s2i_app_ex_standalone
test_python_s2i_app_ex
test_python_imagestream
test_python_s2i_templates
"

set -u
# Pull image before going throw tests
# Exit in case of failure
ct_pull_image "quay.io/centos7/postgresql-10-centos7" "true"

ct_os_set_ocp4

trap ct_os_cleanup EXIT SIGINT

ct_os_check_compulsory_vars

oc status || false "It looks like oc is not properly logged in."

# For testing on OpenShift 4 we use internal registry
export CT_EXTERNAL_REGISTRY=true

test -n "${IMAGE_NAME-}" || false 'make sure $IMAGE_NAME is defined'
test -n "${VERSION-}" || false 'make sure $VERSION is defined'


TEST_SUMMARY=''
TEST_SET=${TESTS:-$TEST_LIST} ct_run_tests_from_testset "openshift-remote-cluster"

# vim: set tabstop=2:shiftwidth=2:expandtab:

