#!/bin/bash
#
# Test the Python image in the OpenShift.
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# VERSION specifies a version of the python in the candidate image.
# The image has to be available before this script is executed.

THISDIR=$(dirname ${BASH_SOURCE[0]})

source "${THISDIR}/test-lib.sh"
source "${THISDIR}/test-lib-openshift.sh"
source "${THISDIR}/test-lib-python.sh"

set -exo nounset

test -n "${IMAGE_NAME-}" || false 'make sure $IMAGE_NAME is defined'
test -n "${VERSION-}" || false 'make sure $VERSION is defined'

ct_os_cluster_up

ct_os_test_s2i_app "${IMAGE_NAME}" "${THISDIR}/standalone-test-app" . "Hello World from standalone WSGI application!"

ct_os_test_s2i_app "${IMAGE_NAME}" "https://github.com/sclorg/django-ex.git" . 'Welcome to your Django application on OpenShift'

ct_os_test_template_app "${IMAGE_NAME}" \
                        https://raw.githubusercontent.com/sclorg/django-ex/master/openshift/templates/django-postgresql.json \
                        python \
                        'Welcome to your Django application on OpenShift' \
                        8080 http 200 "-p SOURCE_REPOSITORY_REF=master -p PYTHON_VERSION=${VERSION} -p POSTGRESQL_VERSION=9.6 -p NAME=python-testing" \
                        "centos/postgresql-96-centos7|postgresql:9.6"

# test with the just built image and an integrated template
test_python_integration "${IMAGE_NAME}" "${VERSION}" python

# test with a released image and an integrated template
if [ "${OS}" == "rhel7" ] ; then
  PUBLIC_IMAGE_NAME=${PUBLIC_IMAGE_NAME:-${REGISTRY:-registry.access.redhat.com/}rhscl/${BASE_IMAGE_NAME}-${VERSION//./}-rhel7}
else
  PUBLIC_IMAGE_NAME=${PUBLIC_IMAGE_NAME:-${REGISTRY:-}centos/${BASE_IMAGE_NAME}-${VERSION//./}-centos7}
fi

export CT_SKIP_UPLOAD_IMAGE=true
test_python_integration python "${VERSION}" "${PUBLIC_IMAGE_NAME}"

OS_TESTSUITE_RESULT=0

ct_os_cluster_down

