#!/bin/bash
#
# Test the Python image in the OpenShift.
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# VERSION specifies a version of the python in the candidate image.
# The image has to be available before this script is executed.

THISDIR=$(dirname ${BASH_SOURCE[0]})

source "${THISDIR}/test-lib.sh"
source "${THISDIR}/test-lib-openshift.sh"
source "${THISDIR}/test-lib-python.sh"
source "${THISDIR}/test-lib-remote-openshift.sh"

TEST_LIST="\
test_python_s2i_app_ex_standalone
test_python_s2i_app_ex
test_python_imagestream
test_python_s2i_templates
test_latest_imagestreams
"

ct_os_set_ocp4

trap ct_os_cleanup EXIT SIGINT

ct_os_check_compulsory_vars || exit $OC_ERR

ct_os_check_login || exit $OC_ERR

ct_os_tag_image_for_cvp "python"

ct_pull_or_import_postgresql || exit $OC_ERR

set -u

# For testing on OpenShift 4 we use internal registry
export CT_OCP4_TEST=true

test -n "${IMAGE_NAME-}" || false 'make sure $IMAGE_NAME is defined'
test -n "${VERSION-}" || false 'make sure $VERSION is defined'


TEST_SUMMARY=''
TEST_SET=${TESTS:-$TEST_LIST} ct_run_tests_from_testset "openshift-remote-cluster"

# vim: set tabstop=2:shiftwidth=2:expandtab:

